# Required for Python 3.10 as of: 2022may29
# https://docs.travis-ci.com/user/languages/python/
os: linux
dist: focal

language: python

jobs:
    include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 2.7
        env: TOX_ENV=wheel,py27-testwheel
      - python: 3.7
        env: TOX_ENV=py37
      - python: 3.8
        env: TOX_ENV=py38
      - python: 3.9
        env: TOX_ENV=py39
      - python: 3.10
        env: TOX_ENV=py310
      - python: 3.10
        env: TOX_ENV=wheel,py3-testwheel
      - python: 3.10
        env: TOX_ENV=flake8
      - python: 3.8
        env: TOX_ENV=mypy2
      - python: 3.8
        env: TOX_ENV=mypy3

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
