# Required for Python 3.7 as of: 2019feb14
# https://docs.travis-ci.com/user/languages/python/
dist: xenial

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37
      - python: 3.6
        env: TOX_ENV=flake8
      - python: 3.7
        env: TOX_ENV=mypy2
      - python: 3.7
        env: TOX_ENV=mypy3

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
